### ISSUE TITLE
MemoDelete command?

### ISSUE THREAD

**Issue by for-coursera** [glidenote/memolist.vim#27]
While your `memolist` is almost perfect in its flexibility and minimalism, would it be possible to add something like `MemoDelete` command? Which, obviously, would ask for a name of a memo (may be allowing to TAB-browse all the memos and / or to select from a list of memos) and then would delete the selected memo.

Thanks!

**Comment by glidenote** [comment]
memolist is very simple vim plugin.

So if you want to delete and rename files, I recommend you to use filer plugins.

 -  [vimfiler.vim](https://github.com/Shougo/vimfiler.vim)
 -  [vim-dirvish](https://github.com/justinmk/vim-dirvish)
 -  [NERD Tree](https://github.com/scrooloose/nerdtree)

Thank you :smile:
